### ISSUE TITLE
Creating an order fails with specific numbers

### ISSUE THREAD

**Issue by sterlu** [ethfinex/efx-api-node#11]
Steps to reproduce: 
- Attempt to create an order with amount of 0.8 and price of 274. `efx.contract.createOrder('ETHUSD', 0.8, 274)`
- error will happen at `src/api/contract/createOrder.js:53` due to a BN being created from a number with decimal points. 

This does not always happen as usually buyAmount/sellAmount have less decimal points than buyCurrency.decimals/sellCurrency.decimals. I believe this is an issue caused by float precision in JS. 

Adding `Math.floor` around `10 ** sellCurrency.decimals * sellAmount` and `10 ** buyCurrency.decimals * buyAmount` seems to solve the problem.

**Comment by hems** [comment]
After multiplying by the number of decimals in the token we already get the highest precision supported so turns out Math.trunc should do the job.

**Comment by hems** [comment]
this should have been fixed, please close the issue if it works for you
