### ISSUE TITLE
Locking tokens can only increase duration

### ISSUE THREAD

**Issue by plutoegg** [ethfinex/efx-api-node#7]
Currently if increasing the number of tokens locked into a wrapper, for a specific token, the transaction fails without giving an error message if the duration of lock specified is less than the current `depositLock` time which the user's tokens are locked for.

When locking additional tokens, the client should first check if there are tokens already locked, and the current remaining time on `depositLock` and then increase the value when locking more tokens.

**Comment by hems** [comment]
I'm not exactly sure to which value we should set "duration" if a user try to lock more tokens.

For instance:

First step:
 - The user locks 1 ETH for 5 hours
 - depositLock becomes `Date.now() / 1000 + 5 hours`

Second step ( let's say user executes this 10 seconds after the first step ):
 - User try to lock 1 ETH for 1 hour
 - depositLock is already `Date.now() / 1000 + 5 hours`

At this point:
 - Is the library responsible for telling the user he can't lock with a duration < 5 hours?
 - Should the library ignore the user 1 hour duration and set it to 5 hours?
 - ...?

**Comment by plutoegg** [comment]
So currently the lock transaction will fail if the duration is not > 5 hours

I believe the library should both warn the user that he can't lock with a duration less than the current duration, and then continue to set duration to 5 hours + 1 hour instead.

If the user wishes to reduce the duration they can first withdraw and then re-deposit.
